image:
  repository: host.docker.internal:8080/library/layered-kserve
  tag: u24-cu128-py312-torch210-mlflow3152-kserve0190-g6
  pullSecrets:
    - harbor-pull

gpu:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi
