apiVersion: v1
kind: Service
metadata:
  name: buildkitd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: buildkitd
  ports:
    - name: buildkit
      port: 1234
      targetPort: buildkit
