apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-g4-kserve-crds
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: g-platform
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve-crd
    targetRevision: v0.20.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
