{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "layered-model.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "layered-model.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
