apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kserve
resources:
  - namespace.yaml
  - marker.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: g-platform
      platform.openai.com/layer: g6
