apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yolo11n-detector
  namespace: model-serving
  annotations:
    serving.kserve.io/deploymentMode: Standard
spec:
  predictor:
    serviceAccountName: layered-model
    minReplicas: 1
    maxReplicas: 1
    containers:
      - name: kserve-container
        image: host.docker.internal:8080/library/yolo-mlflow-kserve:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: MODEL_NAME
            value: yolo11n-detector
          - name: MLFLOW_MODEL_URI
            value: models:/yolo11n-detector@champion
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow-mlflow.mlflow.svc.cluster.local:5000
          - name: YOLO_CONFIG_DIR
            value: /tmp
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 6Gi
